name: Trigger auto deployment for container-app-tu2wiltpo2kpc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-tu2wiltpo2kpc-AutoDeployTrigger-d05112d4-ff03-481e-a9cb-b214bc278471.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistrytu2wiltpo2kpc.azurecr.io
          username: ${{ secrets.CONTAINERAPPTU2WILTPO2KPC_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPTU2WILTPO2KPC_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistrytu2wiltpo2kpc.azurecr.io/container-app-tu2wiltpo2kpc:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPTU2WILTPO2KPC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPTU2WILTPO2KPC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPTU2WILTPO2KPC_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-tu2wiltpo2kpc -g githubactiontestappcontainera96d --server containerregistrytu2wiltpo2kpc.azurecr.io --username  ${{ secrets.CONTAINERAPPTU2WILTPO2KPC_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPTU2WILTPO2KPC_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-tu2wiltpo2kpc -g githubactiontestappcontainera96d --image containerregistrytu2wiltpo2kpc.azurecr.io/container-app-tu2wiltpo2kpc:${{ github.sha }}
