name: Trigger auto deployment for container-app-niqb5mvesatcq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-niqb5mvesatcq-AutoDeployTrigger-820bf7bc-4884-4bef-8aaf-7538ec1ba129.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistryniqb5mvesatcq.azurecr.io
          username: ${{ secrets.CONTAINERAPPNIQB5MVESATCQ_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPNIQB5MVESATCQ_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistryniqb5mvesatcq.azurecr.io/container-app-niqb5mvesatcq:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPNIQB5MVESATCQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPNIQB5MVESATCQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPNIQB5MVESATCQ_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-niqb5mvesatcq -g githubactiontestappcontainer842a --server containerregistryniqb5mvesatcq.azurecr.io --username  ${{ secrets.CONTAINERAPPNIQB5MVESATCQ_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPNIQB5MVESATCQ_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-niqb5mvesatcq -g githubactiontestappcontainer842a --image containerregistryniqb5mvesatcq.azurecr.io/container-app-niqb5mvesatcq:${{ github.sha }}
