name: Trigger auto deployment for container-app-xckcx7rwa2ozo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-xckcx7rwa2ozo-AutoDeployTrigger-0cc50497-9ed3-4b72-8dc8-64cfcc5fdf3f.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistryxckcx7rwa2ozo.azurecr.io
          username: ${{ secrets.CONTAINERAPPXCKCX7RWA2OZO_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPXCKCX7RWA2OZO_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistryxckcx7rwa2ozo.azurecr.io/container-app-xckcx7rwa2ozo:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPXCKCX7RWA2OZO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPXCKCX7RWA2OZO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPXCKCX7RWA2OZO_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-xckcx7rwa2ozo -g githubactiontestappcontainerb13a --server containerregistryxckcx7rwa2ozo.azurecr.io --username  ${{ secrets.CONTAINERAPPXCKCX7RWA2OZO_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPXCKCX7RWA2OZO_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-xckcx7rwa2ozo -g githubactiontestappcontainerb13a --image containerregistryxckcx7rwa2ozo.azurecr.io/container-app-xckcx7rwa2ozo:${{ github.sha }}
