name: Trigger auto deployment for container-app-lccaz6p4dqswk

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-lccaz6p4dqswk-AutoDeployTrigger-313b1471-4ae7-4ab9-b45b-d8e4549329d3.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistrylccaz6p4dqswk.azurecr.io
          username: ${{ secrets.CONTAINERAPPLCCAZ6P4DQSWK_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPLCCAZ6P4DQSWK_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistrylccaz6p4dqswk.azurecr.io/container-app-lccaz6p4dqswk:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPLCCAZ6P4DQSWK__AZURE_TENANT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPLCCAZ6P4DQSWK__AZURE_CLIENT_ID }}
          subscription-id: ${{ _subId_ }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-lccaz6p4dqswk -g githubactiontestappcontainerbd50 --server containerregistrylccaz6p4dqswk.azurecr.io --username  ${{ secrets.CONTAINERAPPLCCAZ6P4DQSWK_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPLCCAZ6P4DQSWK_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-lccaz6p4dqswk -g githubactiontestappcontainerbd50 --image containerregistrylccaz6p4dqswk.azurecr.io/container-app-lccaz6p4dqswk:${{ github.sha }}
