name: Trigger auto deployment for container-app-u232tyuslknmo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-u232tyuslknmo-AutoDeployTrigger-83e83c1d-1cca-400f-849a-f0e295d5a3c3.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistryu232tyuslknmo.azurecr.io
          username: ${{ secrets.CONTAINERAPPU232TYUSLKNMO_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPU232TYUSLKNMO_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistryu232tyuslknmo.azurecr.io/container-app-u232tyuslknmo:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPU232TYUSLKNMO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPU232TYUSLKNMO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPU232TYUSLKNMO_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-u232tyuslknmo -g githubactiontestappcontainer8fce --server containerregistryu232tyuslknmo.azurecr.io --username  ${{ secrets.CONTAINERAPPU232TYUSLKNMO_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPU232TYUSLKNMO_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-u232tyuslknmo -g githubactiontestappcontainer8fce --image containerregistryu232tyuslknmo.azurecr.io/container-app-u232tyuslknmo:${{ github.sha }}
