name: Trigger auto deployment for container-app-rpgwc7oji5jra

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-rpgwc7oji5jra-AutoDeployTrigger-361098bc-2a59-4b11-a95a-a389763ded25.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistryrpgwc7oji5jra.azurecr.io
          username: ${{ secrets.CONTAINERAPPRPGWC7OJI5JRA_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPRPGWC7OJI5JRA_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistryrpgwc7oji5jra.azurecr.io/container-app-rpgwc7oji5jra:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPRPGWC7OJI5JRA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPRPGWC7OJI5JRA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPRPGWC7OJI5JRA_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-rpgwc7oji5jra -g testoidccontainerappInProgress --server containerregistryrpgwc7oji5jra.azurecr.io --username  ${{ secrets.CONTAINERAPPRPGWC7OJI5JRA_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPRPGWC7OJI5JRA_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-rpgwc7oji5jra -g testoidccontainerappInProgress --image containerregistryrpgwc7oji5jra.azurecr.io/container-app-rpgwc7oji5jra:${{ github.sha }}
