name: Trigger auto deployment for container-app-cq2zqewabnfwu

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-cq2zqewabnfwu-AutoDeployTrigger-3ffb2e57-cae5-4409-bdd1-2bff366f085e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      


permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistrycq2zqewabnfwu.azurecr.io
          username: ${{ secrets.CONTAINERAPPCQ2ZQEWABNFWU_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPCQ2ZQEWABNFWU_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistrycq2zqewabnfwu.azurecr.io/container-app-cq2zqewabnfwu:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: f052aebc-16ee-4d0c-8472-cd468a618994
          tenant-id: 72f988bf-86f1-41af-91ab-2d7cd011db47
          subscription-id: d6791cea-23fc-44ab-a870-9b4f28034c61

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-cq2zqewabnfwu -g githubactiontestappcontainerb311 --server containerregistrycq2zqewabnfwu.azurecr.io --username  ${{ secrets.CONTAINERAPPCQ2ZQEWABNFWU_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPCQ2ZQEWABNFWU_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-cq2zqewabnfwu -g githubactiontestappcontainerb311 --image containerregistrycq2zqewabnfwu.azurecr.io/container-app-cq2zqewabnfwu:${{ github.sha }}
