name: Trigger auto deployment for container-app-7ze2pasqwjpiu

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-7ze2pasqwjpiu-AutoDeployTrigger-d570a554-2068-41f3-9b4e-0ea508b19cea.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistry7ze2pasqwjpiu.azurecr.io
          username: ${{ secrets.CONTAINERAPP7ZE2PASQWJPIU_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPP7ZE2PASQWJPIU_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistry7ze2pasqwjpiu.azurecr.io/container-app-7ze2pasqwjpiu:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP7ZE2PASQWJPIU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP7ZE2PASQWJPIU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP7ZE2PASQWJPIU_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-7ze2pasqwjpiu -g githubactiontestappcontainer8b9a --server containerregistry7ze2pasqwjpiu.azurecr.io --username  ${{ secrets.CONTAINERAPP7ZE2PASQWJPIU_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPP7ZE2PASQWJPIU_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-7ze2pasqwjpiu -g githubactiontestappcontainer8b9a --image containerregistry7ze2pasqwjpiu.azurecr.io/container-app-7ze2pasqwjpiu:${{ github.sha }}
