name: Trigger auto deployment for testoidc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/testoidc-AutoDeployTrigger-72a4e0a7-447b-488e-b20f-ae7c81cdb2d7.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: testoidc.azurecr.io
          username: ${{ secrets.TESTOIDC_REGISTRY_USERNAME }}
          password: ${{ secrets.TESTOIDC_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: testoidc.azurecr.io/testoidc:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTOIDC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTOIDC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTOIDC_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n testoidc -g DRDrill --server testoidc.azurecr.io --username  ${{ secrets.TESTOIDC_REGISTRY_USERNAME }} --password ${{ secrets.TESTOIDC_REGISTRY_PASSWORD }}
            az containerapp update -n testoidc -g DRDrill --image testoidc.azurecr.io/testoidc:${{ github.sha }}
